#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, isAbsolute, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  buildPresetShapeCatalog,
  loadPinnedPresetShapeDefinitions,
  stableJson,
} from './source-validator.mjs';
import {
  compilePresetShapeDefinitions,
  evaluatePresetShape,
  summarizePresetGeometryIr,
} from './geometry-ir.mjs';
import { emitPresetShapePaths, summarizeEmittedPresetShape } from './path-emitter.mjs';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const defaultRepositoryRoot = resolve(scriptDirectory, '../..');
const defaultOutput = 'scripts/ooxml-geometry/generated/preset-shape-catalog.json';
const defaultRuntimeOutput = 'src/shapes/generated/ooxmlPresetGeometrySubset.ts';
const runtimeShapeNames = Object.freeze([
  'flowChartProcess', // MsoAutoShapeType 61
  'flowChartAlternateProcess', // 62
  'flowChartDecision', // 63
  'flowChartInputOutput', // 64 (PowerPoint label: Flowchart Data)
  'flowChartDocument', // 67
  'flowChartTerminator', // 69
  'flowChartPreparation', // 70
  'flowChartManualInput', // 71
  'flowChartManualOperation', // 72
  'flowChartConnector', // 73
  'flowChartOffpageConnector', // 74
  'flowChartPunchedCard', // 75 (PowerPoint label: Flowchart Card)
  'flowChartPunchedTape', // 76
  'flowChartCollate', // 79
  'flowChartExtract', // 81
  'flowChartMerge', // 82
  'flowChartOnlineStorage', // 83 (PowerPoint label: Flowchart Stored Data)
  'flowChartDelay', // 84
  'flowChartMagneticTape', // 85 (PowerPoint label: Sequential Access Storage)
  'flowChartDisplay', // 88
]);
const evaluationProfiles = Object.freeze([
  { name: 'square', width: 216, height: 216 },
  { name: 'wide', width: 400, height: 180 },
  { name: 'tall', width: 180, height: 400 },
]);

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'));
}

export async function writeOrCheckGeneratedCatalog({
  artifactLabel = 'OOXML geometry catalog',
  check = false,
  generated,
  outputPath,
}) {
  if (check) {
    let current;
    try {
      current = await readFile(outputPath, 'utf8');
    } catch (error) {
      if (error?.code === 'ENOENT') {
        throw new Error(`Generated ${artifactLabel} is missing: ${outputPath}`);
      }
      throw error;
    }
    if (current !== generated) {
      throw new Error(
        `Generated ${artifactLabel} is stale: ${outputPath}. Run pnpm geometry:generate.`,
      );
    }
    return { outputPath, status: 'current' };
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, generated, 'utf8');
  return { outputPath, status: 'generated' };
}

export function buildRuntimeGeometryModule(ir, shapeNames = runtimeShapeNames) {
  const shapeByName = new Map(ir.shapes.map((shape) => [shape.name, shape]));
  const definitions = shapeNames.map((name) => {
    const shape = shapeByName.get(name);
    if (!shape) throw new Error(`OOXML runtime subset shape is missing from source: ${name}`);
    if (shape.paths.length !== 1) {
      throw new Error(
        `OOXML runtime subset shape must contain exactly one path until multi-path routing is supported: ${name}`,
      );
    }
    if (shape.adjustmentGuides.length !== 0) {
      throw new Error(
        `OOXML runtime subset shape must not contain adjustment guides until adjustment bounds are gated: ${name}`,
      );
    }
    return {
      name: shape.name,
      adjustmentGuides: shape.adjustmentGuides,
      calculatedGuides: shape.calculatedGuides,
      paths: shape.paths,
    };
  });
  if (new Set(shapeNames).size !== shapeNames.length) {
    throw new Error('OOXML runtime subset shape names must be unique');
  }
  const sourceSha256 = ir.source?.presetShapeDefinitions?.sha256;
  if (!/^[a-f0-9]{64}$/.test(sourceSha256 ?? '')) {
    throw new Error('OOXML runtime subset requires a valid preset source SHA-256');
  }
  const serializedDefinitions = stableJson(definitions).trimEnd();
  return `// Generated by scripts/ooxml-geometry/generate.mjs. Do not edit manually.
// Source: ECMA-376 DrawingML presetShapeDefinitions.xml (${sourceSha256})

export const OOXML_PRESET_GEOMETRY_SOURCE_SHA256 = '${sourceSha256}';

export const OOXML_PRESET_GEOMETRY_DEFINITIONS = ${serializedDefinitions} as const;
`;
}

export function buildGeometryIrContract(ir) {
  const structuralBytes = stableJson({ schemaVersion: ir.schemaVersion, shapes: ir.shapes });
  const profiles = evaluationProfiles.map((profile) => {
    for (const shape of ir.shapes) {
      evaluatePresetShape(shape, profile);
    }
    return { ...profile, evaluatedShapes: ir.shapes.length };
  });
  return {
    schemaVersion: ir.schemaVersion,
    structuralSha256: createHash('sha256').update(structuralBytes).digest('hex'),
    summary: summarizePresetGeometryIr(ir),
    evaluationProfiles: profiles,
  };
}

export function buildPathEmissionContract(ir) {
  const precision = 6;
  const profiles = evaluationProfiles.map((profile) => {
    const emittedShapes = ir.shapes.map((shape) =>
      emitPresetShapePaths(evaluatePresetShape(shape, profile), { precision }),
    );
    const summaries = emittedShapes.map((shape) => summarizeEmittedPresetShape(shape));
    const emittedPaths = summaries.reduce((total, summary) => total + summary.paths, 0);
    const nonEmptyPaths = summaries.reduce((total, summary) => total + summary.nonEmptyPaths, 0);
    if (nonEmptyPaths !== emittedPaths) {
      throw new Error(
        `OOXML path emission produced ${emittedPaths - nonEmptyPaths} empty paths for ${profile.name}`,
      );
    }
    return {
      ...profile,
      emittedShapes: emittedShapes.length,
      emittedPaths,
      nonEmptyPaths,
      nonFiniteTokens: summaries.reduce((total, summary) => total + summary.nonFiniteTokens, 0),
      sha256: createHash('sha256').update(stableJson(emittedShapes)).digest('hex'),
    };
  });
  return { schemaVersion: 1, precision, profiles };
}

function parseArguments(arguments_) {
  const options = {
    check: false,
    output: defaultOutput,
    runtimeOutput: defaultRuntimeOutput,
    repositoryRoot: defaultRepositoryRoot,
  };
  for (let index = 0; index < arguments_.length; index += 1) {
    const argument = arguments_[index];
    if (argument === '--check') {
      options.check = true;
      continue;
    }
    if (argument === '--output') {
      const value = arguments_[index + 1];
      if (!value) throw new Error('--output requires a path');
      options.output = value;
      index += 1;
      continue;
    }
    if (argument === '--root') {
      const value = arguments_[index + 1];
      if (!value) throw new Error('--root requires a path');
      options.repositoryRoot = resolve(value);
      index += 1;
      continue;
    }
    if (argument === '--runtime-output') {
      const value = arguments_[index + 1];
      if (!value) throw new Error('--runtime-output requires a path');
      options.runtimeOutput = value;
      index += 1;
      continue;
    }
    throw new Error(`Unknown argument: ${argument}`);
  }
  return options;
}

export async function generatePresetShapeCatalog({
  check = false,
  output = defaultOutput,
  runtimeOutput = defaultRuntimeOutput,
  repositoryRoot = defaultRepositoryRoot,
} = {}) {
  const manifestPath = resolve(repositoryRoot, 'scripts/ooxml-geometry/source-manifest.json');
  const reconciliationPath = resolve(
    repositoryRoot,
    'scripts/ooxml-geometry/source-reconciliation.json',
  );
  const manifest = await readJson(manifestPath);
  const reconciliation = await readJson(reconciliationPath);
  const source = await loadPinnedPresetShapeDefinitions(repositoryRoot, manifest);
  const sourceCatalog = buildPresetShapeCatalog(source.xml, manifest, reconciliation);
  const geometryIr = compilePresetShapeDefinitions(source.xml, manifest, reconciliation);
  const catalog = {
    ...sourceCatalog,
    geometryIr: buildGeometryIrContract(geometryIr),
    pathEmission: buildPathEmissionContract(geometryIr),
  };
  const generated = stableJson(catalog);
  const outputPath = isAbsolute(output) ? output : resolve(repositoryRoot, output);
  const persisted = await writeOrCheckGeneratedCatalog({ check, generated, outputPath });
  const runtimeGenerated = buildRuntimeGeometryModule(geometryIr);
  const runtimeOutputPath = isAbsolute(runtimeOutput)
    ? runtimeOutput
    : resolve(repositoryRoot, runtimeOutput);
  const runtimePersisted = await writeOrCheckGeneratedCatalog({
    artifactLabel: 'OOXML geometry runtime subset',
    check,
    generated: runtimeGenerated,
    outputPath: runtimeOutputPath,
  });
  return { catalog, ...persisted, runtimeOutputPath, runtimeStatus: runtimePersisted.status };
}

async function main() {
  const options = parseArguments(process.argv.slice(2));
  const result = await generatePresetShapeCatalog(options);
  const summary = result.catalog.summary;
  console.log(
    `${result.status}: ${result.outputPath} (${summary.uniqueShapes} shapes, ${summary.guideFormulas} formulas, ${summary.paths} paths)`,
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
